qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs1_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs16_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 126 --stride_A 126 --stride_B 126 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps126_bs160_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs1_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 128 --stride_A 128 --stride_B 128 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps128_bs16_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs1_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 188 --stride_A 188 --stride_B 188 --netG resnet_9blocks --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps188_bs16_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 1 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs1_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 16 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs16_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm batch --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_batchnorm_lr_cosine_wr_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_step_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_step_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_step_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy step --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_step_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_cosine_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_cosine_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_cosine_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_cosine_vanillaLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode lsgan --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_cosine_wr_lr_lsganLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode lsgan --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_cosine_wr_lsganLoss_no_idt
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode vanilla --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_cosine_wr_lr_vanillaLoss_idt_true
qsub ./train.sh ./train_new.py --patch_size 190 --stride_A 190 --stride_B 190 --netG unet_32 --batch_size 160 --norm instance --lr_policy cosine_wr --gan_mode vanilla --lambda_identity 0 --use_wandb --no_html --name cgan2D_ps190_bs160_instancenorm_lr_cosine_wr_vanillaLoss_no_idt
